### ISSUE TITLE
License not included in repo

### ISSUE THREAD

**Issue by lafrenierejm** [i-tu/Hasklig#100]
Is there any particular reason Hasklig does not include a copy of the OFL?

**Comment by arrowd** [comment]
As FreeBSD packager I'd also like to see LICENSE file.

**Comment by jbaginski** [comment]
@i-tu can you please provide LICENSE file?

**Comment by i-tu** [comment]
Hi, the repo is licensed under SIL, and there is a LICENSE.md file reflecting this now.
