### ISSUE TITLE
FYI Works in Notepad3 & Notepad++

### ISSUE THREAD

**Issue by lucknaumann** [i-tu/Hasklig#120]
Copied the [ligatures ](https://github.com/i-tu/Hasklig#currently-implemented-symbols) from the README. Displayed correctly in both editors.

Edit: meant to reference how to get [Ligatures to work](https://github.com/rizonesoft/Notepad3/issues/361#issuecomment-587458073) in Notepad3 (there's an [issue](https://github.com/rizonesoft/Notepad3/issues/361#issuecomment-587452720) that's being addressed).

> As a workaround ... use [Settings] RenderingTechnology= (e.g. by Menu -> Settings -> Technology -> Rendering -> DirectWrite (Direct2D)).

**Comment by i-tu** [comment]
I decided to remove the compatibility list as it is probably out of date. Ligatures have become pretty mainstream now too. The Fira Code repository maintains a list that is the probably the best one available: https://github.com/tonsky/FiraCode
