### ISSUE TITLE
No color on macOS Big Sur

### ISSUE THREAD

**Issue by balupton** [i-tu/Hasklig#123]
- https://github.com/adobe-fonts/source-code-pro/issues/250
- https://github.com/microsoft/vscode/issues/100840
- https://bugs.chromium.org/p/chromium/issues/detail?id=1100502

**Comment by theLMGN** [comment]
This seems to be an issue with a SVG table, we need someone to remove those from Hasklig to regain support

**Comment by patricklewis** [comment]
Took me a while to identify the font as the source of this "no text color" problem in Visual Studio Code after upgrading to Big Sur today.

**Comment by hisham-blackbuck** [comment]
any workarounds for this? Reinstalling Hasklig did not fix the issue, and while disabling Hasklig is the only workaround now, my code looks bland without Hasklig :cry:

**Comment by thedocbwarren** [comment]
Would love a solution.  Appears other fonts work that have ligatures.

**Comment by 1moeses** [comment]
Is there someone who can do a pull request. Unfortunally I'm not into font-coding-stuff right now. The last commit was on Feb. 27, 2020. Looong time ago.

**Comment by thedocbwarren** [comment]
Will need to build from the patched (remove SVG table) from Source Code Pro then add ligatures.  I wish I did this these days as I use to make fonts, but not recently.

**Comment by labikmartin** [comment]
> any workarounds for this? Reinstalling Hasklig did not fix the issue, and while disabling Hasklig is the only workaround now, my code looks bland without Hasklig 😢

You can use `Source Code Pro` in the meantime.

**Comment by hisham-blackbuck** [comment]
I believe Source Code Pro has slightly different ligatures. For example, the arrow function symbol is different. Correct me if I'm wrong here

**Comment by labikmartin** [comment]
> I believe Source Code Pro has slightly different ligatures. For example, the arrow function symbol is different. Correct me if I'm wrong here

That font doesn't have ligatures. But other than that it looks the same :)

**Comment by hisham-blackbuck** [comment]
Oh then I'll have to wait till Hasklig fixes this, because I need those ligatures. I could try Fira Code in the meantime

**Comment by tovbinm** [comment]
Switching to Source Code Pro worked - https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro%2F1.052R-it%2F1.012R-VAR

Looking forward for a similar fix for Hasklig!

**Comment by thedocbwarren** [comment]
Looking at last update I'd say this might be unmaintained.  Not sure how this font was generated from Source Code Pro.
I'm going to guess this could be from a script that merged ligatures from Fira Code.

**Comment by jonboiser** [comment]
This repo is a fork of the original Source Code Pro repo. You can see in a commit like this one https://github.com/i-tu/Hasklig/commit/fe063b4cc66eabfa6fb949b9fb07c26d2a555862 one of the last updates from the upstream repo.

I'm not sure how these updates were done, but it might be possible to update to the latest SCP source, and run the build scripts.

**Comment by ehrlichja** [comment]
I fixed this problem on my Big Sur installation. I deleted Haskling from Font Book and re-installed it using Brew.

The problem was only showing up in Alacritty for me, but the above steps fixed it.

**Comment by tovbinm** [comment]
@ehrlichja That did not work for me.

**Comment by thedocbwarren** [comment]
It doesn't work work anybody.  Hasklig needs to be updated directly with the fixes to remove invalid SVG gliffs.

**Comment by georgefst** [comment]
Source Code Pro has [removed the SVG table](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.032R-ro/1.052R-it/1.012R-VAR). I think the same fix is in order here.

If no one else steps up, I'll have a look at opening a PR porting the fix. But it might be easier for someone who already knows anything about creating fonts.

**Comment by thedocbwarren** [comment]
Agreed, I'm not 100% sure what is needed but can look as well.

**Comment by pkq** [comment]
Font development is well outside my comfort zone, but I *believe* this issue is resolved by #125. Until these changes are merged, you should be able to build the font from source using the [SVGpatch branch](https://github.com/pkq/Hasklig/tree/SVGpatch) and [the directions in the README.md](https://github.com/i-tu/Hasklig#building-the-fonts-from-source).

**Comment by mbg** [comment]
#125 / v1.2 have resolved this issue for me on Big Sur.

**Comment by i-tu** [comment]
Thank you @pkq for looking into this, and thanks @mbg for confirming 👍 

The new release can be downloaded here: https://github.com/i-tu/Hasklig/releases/tag/v1.2

Do let me know if you have any issues.

Happy winter solstice and related festivities to all! :)

**Comment by jonboiser** [comment]
I've submitted a PR to update the homebrew cask for this font (my preferred installation method)

https://github.com/Homebrew/homebrew-cask-fonts/pull/3301
