### ISSUE TITLE
Mention support in Vico.

### ISSUE THREAD

**Issue by jordwalke** [i-tu/Hasklig#13]
I discovered that Vico editor appears to render ligatures just fine (someone should confirm).
https://github.com/vicoapp/vico
It's also a pretty cool editor with a faithful Vim mode.

**Comment by i-tu** [comment]
Thanks @jordwalke, [I added this information to the readme.](https://github.com/i-tu/Hasklig/commit/4fb4ee5471b154acd6d871b417f18ccad1e3fd3b)

**Comment by jordwalke** [comment]
:+1:
