### ISSUE TITLE
SCP 2.0 has landed, time for Hasklig to be updated

### ISSUE THREAD

**Issue by ldmldmldm** [i-tu/Hasklig#17]
Hello.

Thanks for your hard work on Hasklig. Incase you haven't heard, SCP 2.0 has landed https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro/1.030R-it so I look forward to an updated version of Hasklig in the near future.

Thanks heaps

**Comment by i-tu** [comment]
Thank you for the heads up. Italics certainly warrant a new release of Hasklig including them.

**Comment by i-tu** [comment]
It took a while, but I'm proud to say that release 0.9 including this change has now landed :)

https://github.com/i-tu/Hasklig/releases/tag/0.9
