### ISSUE TITLE
iTerm2

### ISSUE THREAD

**Issue by onemanstartup** [i-tu/Hasklig#20]
I know it is not supported for now, I just want to subscribe to any news in the regard of iTerm2.

**Comment by evantravers** [comment]
https://twitter.com/mhartington/status/754780805252128768

It's coming… it's in nightlies at the moment. I've been using it for a week, and it's pretty good!

**Comment by i-tu** [comment]
I'm trying to cut down on open issues. iTerm2 support is coming in version 3.1 AFAIK.
