### ISSUE TITLE
Ligature request: =/=

### ISSUE THREAD

**Issue by tuncer** [i-tu/Hasklig#23]
Erlang has `/=` and `=/=` with different semantics, and if I type `=/=`, I get a visible space between `=` on the left and the ligature for `/=` on the right.

Also, am I mistaken, or is `=:=` already included?

**Comment by i-tu** [comment]
Good idea, `=/=` is easy to implement and unlikely to cause conflicts.

`=:=` is not implemented yet. What do you think it should look like? Parallel lines with dots above and below, or parallel lines with dots breaking them?

**Comment by tuncer** [comment]
Breaking them.

**Comment by tuncer** [comment]
I think breaking them would be good, but seeing the variants first would help a lot.

**Comment by yueyoum** [comment]
:+1: 

I also need `=/=`

**Comment by tuncer** [comment]
@i-tu, to be clear, `=/=` should be the mathematical not-equals symbol.

Do you think we could alternatively use the triple bar equals symbol (U+2261) for `=:=`, instead of a totally new one? Would that make sense?
