### ISSUE TITLE
Weird ligature issues

### ISSUE THREAD

**Issue by matthew-dean** [i-tu/Hasklig#24]
The arrow ligature doesn't seem to work for me, and the triple equals only works when followed by another equals sign. (See attachment)

<img width="181" alt="screen shot 2015-09-14 at 3 47 54 pm" src="https://cloud.githubusercontent.com/assets/414752/9863802/247dc0d6-5af8-11e5-8c20-fd5d9a9e9843.png">

**Comment by i-tu** [comment]
What editor are you using?

**Comment by matthew-dean** [comment]
Ace. However, this seems to be working again.
