### ISSUE TITLE
Doesn't work with Chromium 41 / NW.js 0.12.x

### ISSUE THREAD

**Issue by matthew-dean** [i-tu/Hasklig#28]
While Hasklig ligatures work, if you toggle ```text-rendering: optimizeLegibility``` (needed for ligatures) on NW.js 0.12.x, which is using embedded Chromium 41.0.2272.76, the line-length of the "monospaced" font changes. ```text-rendering: geometricPrecision``` has the same error.

See: https://github.com/Crunch/Crunch-2/issues/39

This is probably why support has been difficult for Chromium-based editors like Atom. The Hasklig font simply doesn't render as a monospace font.

**Comment by i-tu** [comment]
As this has been fixed in Atom 1.1.0, I'm closing this issue for now.

**Comment by matthew-dean** [comment]
Uh, okay... but this wasn't an Atom issue. This is a NWJS issue. The long and short is that, in the case of Hasklig the font character width is larger than the browser thinks it is, which is not the case for Source Code Pro, so I don't see how it's a Chromium problem and not a font problem. Or, possibly both, but seems like there would be a way to get the browser to measure Hasklig correctly if it can measure Source Code Pro correctly.

**Comment by matthew-dean** [comment]
So, to be clear, this is still an issue.

**Comment by i-tu** [comment]
Oh, ok. I'll try to figure out what's going on and hopefully come up with a fix.

**Comment by i-tu** [comment]
https://github.com/Crunch/Crunch-2/issues/39#issuecomment-149329680

**Comment by matthew-dean** [comment]
Yes, sorry I didn't follow up!
