### ISSUE TITLE
Support added in BBEdit 11

### ISSUE THREAD

**Issue by 153957** [i-tu/Hasklig#3]
According to the [release notes](http://www.barebones.com/support/bbedit/current_notes.html) of BBEdit 11 font ligatures are now supported:

> You can now turn on font ligatures with an expert preference. This allows enhanced text rendering behavior in certain fonts, such as the work-in-progress Hasklig font which uses ligatures to enhance the display of compound-character Haskell operators.
> 
> Ligatures may be enabled or disabled per font based on the font's display name. So, if you wanted to enable ligatures only for the Hasklig font, you would do it thusly:
> 
> `defaults write com.barebones.bbedit EnableFontLigatures -bool NO`
> `defaults write com.barebones.bbedit EnableFontLigatures_Hasklig -bool YES`
> 
> The font's display name is the name as it appears in the "Fonts" panel or in the Font Book application; not the name of the font file on disk.

**Comment by attaboy** [comment]
Note that for Fira Code, the key must be added in quotes to preserve the space:

`defaults write com.barebones.bbedit "EnableFontLigatures_Fira Code" -bool YES`
