### ISSUE TITLE
Readme is outdated - MacVim now as optional support for ligatures.

### ISSUE THREAD

**Issue by Shirk** [i-tu/Hasklig#32]
I think the title says it all - I worked on a PR which recently got merged into mainline MacVim which enables ligature support for the CoreText renderer :smile_cat:

**Comment by i-tu** [comment]
That's great! Can you provide some more information, like a link to the PR? Which release includes or is scheduled to include this feature?

**Comment by Shirk** [comment]
Sure,
The implementation is in PR [#56](https://github.com/macvim-dev/macvim/pull/56) closing issue [#36](https://github.com/macvim-dev/macvim/issues/36).
It was merged on August 23rd and is part of MacVim Snapshot 79 released on October 31st.

Here are some visuals:
![ligature-demo](https://cloud.githubusercontent.com/assets/304352/8638098/46592860-28af-11e5-8ba1-968e6dbd39b4.gif)
![demo](https://cloud.githubusercontent.com/assets/304352/9423686/800790f2-48cf-11e5-9312-8badf8bedfe4.gif)

**Comment by i-tu** [comment]
Thank you a LOT for doing this, great work! :)

**Comment by lozandier** [comment]
This doesn't seem to work with the recent versions of MacVim; was this highly-anticipated feature disabled for a reason not explicitly made clear in the release branch notes of more recent releases of MacVim?

**Comment by Shirk** [comment]
No, the latest snapshot builds still have it.
But by community decision it was further improved.

The GUI option was converted to a vimrc option.
You can now do `set macligatures` to toggle them on the fly.

**Comment by lozandier** [comment]
Ah, thanks for taking the time to clear this up!

On Fri, Dec 4, 2015 at 11:49 AM, Shirk <notifications@github.com> wrote:

> No, the latest snapshot builds still have it.
> But by community decision it was further improved.
>
> The GUI option was converted to a vimrc option.
> You can now do set macligatures to toggle them on the fly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i-tu/Hasklig/issues/32#issuecomment-162017693>.
>



-- 
Kevin Lozandier
lozandier@gmail.com <lozandier@gmail.com>

**Comment by joaomilho** [comment]
<img width="685" alt="screen shot 2016-01-13 at 10 01 20 pm" src="https://cloud.githubusercontent.com/assets/308196/12306218/4bdfc6a8-ba41-11e5-893c-f43951820a53.png">

I have the right MacVim version, the right font, and ligatures enabled, but still... It actually worked randomly using Fira Code, say, 3% of the time :/

Any idea?

**Comment by Shirk** [comment]
Hmm..   
While I haven't tried with Haskellig yet I'm using Fira Code along with the Core Text renderer and `set macligatures`. 
I see you have `cursorline` enabled *(finally I'm not alone!)* - could you maybe try `set number` and `set relativenumber` in addition? 

It shouldn't make a difference since the ligatures option now forces redraws of it's own but might be worth a try..

**Comment by joaomilho** [comment]
Mmm, doesn't make any difference. What is Core Text renderer, BTW?

**Comment by Shirk** [comment]
If you look at the animated GIF in my second comment you can see the option. 
It's located in the Gui settings dialogue.

**Comment by Shirk** [comment]
@joaomilho - I think I found your problem (and I have to say it's likely a limitation of what we currently can do in the renderer in MacVim).

MacVim requires all characters forming a ligature to be rendered in one go (e.g `<+>` have to be detected in sequence). However the Vim core which is issuing the drawing commands to all GUI frontends is implemented in a way that it will issue multiple drawing calls for differently colored characters.
(There also is currently an open issue with ligatures if you use colorcolumn for the same reason).

You can check by disabling syntax highlighting:
![ligatures-syntax-impact](https://cloud.githubusercontent.com/assets/304352/12332602/a94066dc-baef-11e5-8d94-74a8924a8b0c.gif)

It's best visible in line 5 here where all of the `<X>` triples switch between normal and ligature rendering.

**Comment by joaomilho** [comment]
I actually experience no difference by setting with `:syntax off`.

**Comment by Shirk** [comment]
Did you check the GUI settings for the CoreText renderer?
![coretext renderer](https://cloud.githubusercontent.com/assets/304352/12336199/6ef7da82-bb03-11e5-9aa7-ea6edb1f9a96.png)

I'm currently testing on an in-between-88-and-89 version and it works fine for me.

**Comment by joaomilho** [comment]
Yeap, both with and without.

**Comment by joaomilho** [comment]
Actually closing after changing the config makes it work, __sometimes__. With the syntax off works consistently, but with syntax on in some places, and it adds a red background in the ones that fail. Kinda like...
<img width="312" alt="screen shot 2016-01-14 at 10 50 10 pm" src="https://cloud.githubusercontent.com/assets/308196/12337186/30c993f0-bb11-11e5-84d5-94d31aa0389c.png">
<img width="319" alt="screen shot 2016-01-14 at 10 49 58 pm" src="https://cloud.githubusercontent.com/assets/308196/12337187/30cb7544-bb11-11e5-977b-1e511e79ef34.png">

**Comment by joaomilho** [comment]
I suppose this will depend on the filetype... (2 mins later) ... yeah, of course, in a `.hs` file it works correctly since my highlight considers <$> a sequence, while in, say, html it considers $ a tag name and changes the color.

**Comment by joaomilho** [comment]
BTW, what about function => ƒ ? :D

**Comment by Shirk** [comment]
There, now I'm really eager to find your problem.. 
However I'm almost headed for bed - mind sharing your vimrc in a gist or something so I can have a deeper look tomorrow after work? 
(would also be nice to know the plugins you're using)

**Comment by joaomilho** [comment]
I guess you didn't read my last comment, it's actually working fine now :D Thanks a lot.

**Comment by Shirk** [comment]
Ah, yes I didn't read that while posting my comment.. Glad it works now :+1:

**Comment by dashingspidy** [comment]
Greetings,
I'm also facing same problem. Ligatures doesn't effect immediately. I only see them after i go to next line. I do have same settings as above.

**Comment by dashingspidy** [comment]
If i uncheck both "Use Core text renderer" & "Draw marked text inline", it works like a charm.

BTW, i'm using version 8.0.3

**Comment by chrisvacc** [comment]
Yea, it’s all funky for me.

![firagif](https://user-images.githubusercontent.com/8681599/50391870-5a2c3680-0717-11e9-8ad0-dccf2503d349.gif)

Turning off CoreText Renderer just makes everything look terrible

Anything? I really love this feature.
