### ISSUE TITLE
How to build the font ?

### ISSUE THREAD

**Issue by dorian-marchal** [i-tu/Hasklig#33]
I tried to execute `./buildAll.sh` but it seems there is hard mentions of your personal files in it.

How can I build the fonts from the sources ?

I'm on Ubuntu.

**Comment by i-tu** [comment]
Apologies for that. You will need to install the [Adobe Font Development Kit for OpenType](http://www.adobe.com/devnet/opentype/afdko.html), and change the path to `makeInstances` the the one in your system.

**Comment by i-tu** [comment]
There are detailed instructions in `Readme.md` now. Please note that the build process has now changed very recently.
