### ISSUE TITLE
Ligature for (=>) makes fish operator (>=>) ugly

### ISSUE THREAD

**Issue by welf** [i-tu/Hasklig#35]
Please add ligature for (>=>) too. 

Screenshot from Atom Editor: 
<img width="47" alt="fish" src="https://cloud.githubusercontent.com/assets/1454462/11320026/11051e60-909e-11e5-86a4-5b3d44dcaadd.png">

**Comment by Crazycolorz5** [comment]
Going along with this (<=<) should be added as well.

**Comment by i-tu** [comment]
Fixed in [Hasklig 1.1](https://github.com/i-tu/Hasklig/releases/tag/1.1). Thank you for your input!
