### ISSUE TITLE
List of stars get "unmonospaced"

### ISSUE THREAD

**Issue by igorsantos07** [i-tu/Hasklig#39]
I've just installed Hasklig on my Linux Mint and noticed a common "pattern" I had got broken-ish. Images say it better than words:

No-ligature font, normal code
![screenshot_530](https://cloud.githubusercontent.com/assets/532299/12074892/9823f1f6-b154-11e5-8e75-5257b7bf4025.jpg)

FiraCode, stars with ligatures
![screenshot_531](https://cloud.githubusercontent.com/assets/532299/12074898/cc07586e-b154-11e5-93d9-14b2b8fdf472.jpg)

Hasklig, ligatures make the line go further into the column limit
![screenshot_532](https://cloud.githubusercontent.com/assets/532299/12074900/d5d8f028-b154-11e5-9288-7957a2555635.jpg)

I'm pretty sure I didn't add any stars to the last screenshot :)
Shots taken on PHPStorm, but the effect can be seen as well in Pluma/gEdit. Additionally, Storm goes crazy with the cursor in that line, as you can see through the image: it seems the characters are displayed in their correct column, even though the rendering is out of it.

**Comment by i-tu** [comment]
I wasn't able to reproduce this earlier. If you are still having this problem, it is probably solved by [Hasklig 1.1](https://github.com/i-tu/Hasklig/releases/tag/1.1), which no longer applies ligatures to repeated sequences of characters. Thank you for your input!
