### ISSUE TITLE
Update Sublime Text enhancement link

### ISSUE THREAD

**Issue by xiagu** [i-tu/Hasklig#44]
The link in the README (http://sublimetext.userecho.com/topic/433445-/) is dead.

Some cursory searching suggests that http://sublimetext.userecho.com/topics/4719-does-sublimetext-support-programming-ligatures-fontlike-fira-code/ may be a good replacement. It's linked from the FiraCode repository and is also the current highest-voted one.

**Comment by i-tu** [comment]
Thanks :+1:
