### ISSUE TITLE
xfce4-terminal support?

### ISSUE THREAD

**Issue by SethDusek** [i-tu/Hasklig#46]
So I'd really like xfce4-terminal support since I use neovim inside of it and would really like hasklig. I've tried the pre-release version (apparently with support for more clients) and the stable one, and both don't work. I've also tried Konsole but I'm guessing my version is outdated since hasklig doesn't pop up in the font selection and fira mono doesn't work at all (no ligatures). So could xfce4-terminal support be added into the Hasklig font? Or would I have to open a feature request on xfce for ligatures?

**Comment by i-tu** [comment]
I can't really add individual application support to Hasklig, either applications support ligatures or not. (The difference between the stable and pre-release versions is that the latter uses contextual alternates, and this effects application support somewhat, mostly positively)

**Comment by SethDusek** [comment]
@i-tu I just found this font called "monoid" which also has ligatures http://larsenwork.com/monoid/ and it works with libvte terminals (meaning it works with xfce4-terminal and gnome-terminal). Is there any way you can implement ligatures into hasklig like that?

**Comment by i-tu** [comment]
Really? It explicitly says here that it doesn't: https://github.com/larsenwork/monoid

**Comment by SethDusek** [comment]
Oh, I accidentally launched gnome-terminal instead of xfce to test. Anyways it partially works in gnome-terminal (though some ligatures don't work)

I think next I'm going to do a feature request on libvte since that's apparently where I should request ligature support according to some people on the xfce channel
