### ISSUE TITLE
Wrong view of ligature for (->)

### ISSUE THREAD

**Issue by Newlifer** [i-tu/Hasklig#48]
In Qt Creator 3.6.0 (based on Qt 5.5.1, MSVC 2013, 32bit):

![xnj0mex1fa](https://cloud.githubusercontent.com/assets/668546/13807533/8d531362-eb72-11e5-8325-3210df7744c7.png)

**Comment by i-tu** [comment]
Is this still current? Are you able to reproduce this in other editors? If not, please open an issue with the folks developing Qt Creator.

**Comment by i-tu** [comment]
(closing for now, please comment if this is a non- Qt Creator -specific problem)
