### ISSUE TITLE
Wrong letter height

### ISSUE THREAD

**Issue by Newlifer** [i-tu/Hasklig#50]
The letter «Ч» is shorter than others:
![cakskbrjwi](https://cloud.githubusercontent.com/assets/668546/13982888/7ca9c728-f0fd-11e5-9a94-5fddc733739c.png)

Reproduced in in Visual Studio Code.

**Comment by ForNeVeR** [comment]
I can see the same for Cyrillic letter "Н" in Visual Studio 2015:

![image](https://cloud.githubusercontent.com/assets/92793/14013975/c015ab4e-f1d9-11e5-93c1-6a22c7e55768.png)

That's a common problem among Cyrillic letters with two straight lines at the top like "Ч", "Н" and "Ц", but I cannot confirm the problem for Latin "U" and "L".

Here're the Russian and English alphabets screenshots for the comparison. It seems that the full list of problematic letters is "НУЦШЩЫЬ".

![image](https://cloud.githubusercontent.com/assets/92793/14014054/53bf2690-f1da-11e5-9ed2-61f83a91169d.png)

![image](https://cloud.githubusercontent.com/assets/92793/14014075/7e327ca6-f1da-11e5-976c-5e10924dce39.png)

**Comment by ForNeVeR** [comment]
Cyrillic "Н" and Latin "H" are very similar, so I'd start investigation with comparison of these glyphs.

**Comment by i-tu** [comment]
If you increase the font size significantly, does the problem disappear? (this would indicate broken hinting)

Could you confirm whether Source Code Pro has the same problem? (If so, I could make the fix there in upstream)

**Comment by i-tu** [comment]
I can't seem to reproduce this problem in VS Code on OSX
![screen shot 2016-03-24 at 17 06 22](https://cloud.githubusercontent.com/assets/2201932/14021145/ececd03a-f1e2-11e5-9d87-4f7bfbea217a.png)

**Comment by ForNeVeR** [comment]
I can confirm that increasing of font size does fix the problem. Give me a couple of minutes, I'll check it with Source Code Pro. I am sure that different OS'es can render fonts a bit differently, and generally based on my experience with Liberation Mono Powerline and Hasklig, Windows usually gives a bit more problems than OSX.

**Comment by ForNeVeR** [comment]
Well, yes, it's reproducible in Source Code Pro as well in my Visual Studio.

**Comment by i-tu** [comment]
I didn't close this earlier for some reason, but if it was reproducible in Source Code Pro, you should bring this up with the developers there, as it is a bug in SCP.
