### ISSUE TITLE
Cursor does not appear in middle of characters on Atom

### ISSUE THREAD

**Issue by JoeyEremondi** [i-tu/Hasklig#55]
I'm not sure if this is an Atom issue or a Hasklig one. There's an issue open at Atom here: https://github.com/atom/atom/issues/11567#issuecomment-213211305

Basically, with other fonts, like FiraCode, when you move the cursor through a ligature, it shows the cursor inside the ligature.

With Hasklig, it always shows the cursor on one side, which has led me to make many erroneous edits. 

Is there something in the design of Hasklig vs FiraCode that would cause it? I much prefer the look of Hasklig, so it would be great if this issue were resolved.

**Comment by i-tu** [comment]
Hi Joey,

updating to [1.0 beta](https://github.com/i-tu/Hasklig/releases/tag/v1.0-beta) should resolve this issue :)

**Comment by i-tu** [comment]
As 1.1 was recently released, this issue can be closed.
