### ISSUE TITLE
Ligature Request: <=>

### ISSUE THREAD

**Issue by Kerrick** [i-tu/Hasklig#59]
Ruby supports the "spaceship" operator, but Hasklig makes it look a bit funny. It'd be great to see something like the existing `<+>` ligature, but for `<=>`.

<img width="259" alt="untitled_3_rtf" src="https://cloud.githubusercontent.com/assets/552093/15342625/8db98136-1c5c-11e6-8e0e-b10be01a44c5.png">

**Comment by 2426021684** [comment]
Similar problem for >=>.

**Comment by asethwright** [comment]
Also <->

**Comment by i-tu** [comment]
`<=>`, `>=>`, `<=<`, and `<->` shipped in [Hasklig 1.1](https://github.com/i-tu/Hasklig/releases/tag/1.1). Thank you for your input!
