### ISSUE TITLE
Ligatures in IntelliJ 

### ISSUE THREAD

**Issue by gAmUssA** [i-tu/Hasklig#60]
Intellij Idea now supports ligatures http://blog.jetbrains.com/idea/2016/06/intellij-idea-2016-2-eap-case-only-renames-in-git-ligatures-background-images-and-more/

**Comment by ForNeVeR** [comment]
@gAmUssA it works almost okay but see #56.

**Comment by gAmUssA** [comment]
is it idea’s bug or font?
is it’s a idea’s bug we should follow up with JB.
Let me know what do you think.
Thank you

On Thu, Jun 16, 2016 at 9:00 AM Friedrich von Never <
notifications@github.com> wrote:

> @gAmUssA <https://github.com/gAmUssA> it works almost okay but see #56
> <https://github.com/i-tu/Hasklig/issues/56>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/i-tu/Hasklig/issues/60#issuecomment-226477759>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAabvSvz8dXWlaPHUwt_0TK5x4YIZDxkks5qMUjlgaJpZM4IszVC>
> .
>
-- 
*Viktor Gamov*
*Senior Solution Architect*
Hazelcast | Open source in-memory data grid
275 7th Ave, New York, NY 10001 USA
@gamussa
+1 (201) 355-6226

**Comment by ForNeVeR** [comment]
I am not sure if it's IDEA bug or something wrong with Haslkig's italic type. Still needs to be investigated.

**Comment by i-tu** [comment]
Closing this for now
