### ISSUE TITLE
/= looks like "not equal"

### ISSUE THREAD

**Issue by mpetersen** [i-tu/Hasklig#61]
To me the "/=" ligature looks like "not equal", and not like an assignment operator. I recommend to abandon this ligature or make it clearer. Since there are no ligatures for +=, *= and -=, I don't see any benefit in this ligature anyways, and it is confusing, because it looks similar to "==" but this is not an assignment operator.

**Comment by ahammel** [comment]
'/=' is the "not equal" operator in Haskell.

**Comment by mpetersen** [comment]
Ah crap, sorry. I was looking through the Java glass (coming from IntelliJ IDEA). 
However, this renders this font useless for Java.

**Comment by i-tu** [comment]
This is a good point though, and differing fonts based on operators of different programming languages are something that is worth looking into.
