### ISSUE TITLE
add codepoint for ∘

### ISSUE THREAD

**Issue by knupfer** [i-tu/Hasklig#65]
Having a extra codepoint for the compositionoperator with a width of 3 chars, one could easily fontify these in emacs without fontifying name spaces

**Comment by i-tu** [comment]
To clarify: do you mean that there should be a character like this:  "` ∘ `" with a custom unicode code point?

**Comment by knupfer** [comment]
Exactly, this allows to substitute `" ∘ "` via `prettify-symbols-mode`. So you'd have the composition operator only with proper spacing. This avoids fontifying a single dot in a qualified function.

**Comment by i-tu** [comment]
After consideration: in this form, this is out of scope. I don't want to do custom unicode code points. It could probably be done in OpenType, but in the philosophy I've been following in Hasklig, I haven't been changing characters to look different (` . ` to ` ∘ `).
