### ISSUE TITLE
add ∨ and ∧ as extracodepoints

### ISSUE THREAD

**Issue by knupfer** [i-tu/Hasklig#66]
with these in the width of 2 chars, you could in emacs easily fontify || and && to the mathematical notation

**Comment by i-tu** [comment]
Sounds like an easy win. I will get back to you on this.

**Comment by i-tu** [comment]
Sorry to switch sides on this, but with the same rationale as https://github.com/i-tu/Hasklig/issues/65#issuecomment-274329131, I don't think this should be part of Hasklig.
