### ISSUE TITLE
Ligatures for ==== and ----

### ISSUE THREAD

**Issue by konsultaner** [i-tu/Hasklig#71]
The `====` and `----` is never used in any programming Lanuage, but it is used in markdown to define titels and subtitels. It would be very pretty if those ligatures rendered into full lines without any spacing at the left and right end.

``` markdown

Title
========

Subtitle
--------

```

**Comment by i-tu** [comment]
I'm judging that this suggestion is not getting support, and it is not something I'm personally interested in. I won't work on this, but I invite you to roll your own fork, it's not hard to do :)
