### ISSUE TITLE
Should work in Xcode without need for plugin

### ISSUE THREAD

**Issue by mluisbrown** [i-tu/Hasklig#74]
The [FiraCode](https://github.com/tonsky/FiraCode) font which has a similar objective works in Xcode 7.3.1 and Xcode 8 (beta) without the need for a [plugin](https://github.com/robertvojta/LigatureXcodePlugin) to handle ligatures. I have no idea how they managed this but it would be great if Hasklig also supported it.

**Comment by vikky49** [comment]
It seems to be working with the latest beta version of  the fonts

**Comment by mluisbrown** [comment]
Yes, the latest beta works with Xcode without the need for a plugin 👍
