### ISSUE TITLE
Clojure thread-last macro ->> please

### ISSUE THREAD

**Issue by adjl** [i-tu/Hasklig#80]
It would be awesome to have a ligature for [`->>`](https://clojuredocs.org/clojure.core/-%3E%3E), to pair up with `->`. :)

Just a simple request, and thanks for your hard work!

Cheers

**Comment by i-tu** [comment]
Shipped in [Hasklig 1.1](https://github.com/i-tu/Hasklig/releases/tag/1.1). Thank you for your input!
