### ISSUE TITLE
Looks dead

### ISSUE THREAD

**Issue by emcek** [i-tu/Hasklig#82]
I really like that font (much more than FiraCode) but there are not so mamy ligatures here :(

But this looks like dead repo :(

**Comment by vikky49** [comment]
Thats true .I also personally like this font better than Fira code but its missing some ligatures that we use in day to day life like != , >= and <= etc etc . And i don't see any updates happening here

**Comment by zeke** [comment]
cc @i-tu and @miguelsousa in case they're not subscribe to issue notifications on this repo.

**Comment by i-tu** [comment]
I felt a pang of regret upon reading this, since I've been neglecting Hasklig for a while now. Today I released version 1.0, which has no new ligatures, but includes the updates made previously to 1.0-beta and upstream in Source Code Pro

Thanks for reaching out and giving me some motivation :)

**Comment by zeke** [comment]
👍
