### ISSUE TITLE
Request: Slashed zero version

### ISSUE THREAD

**Issue by cobrabr** [i-tu/Hasklig#83]
Just that, really. :smile: 

I really like Hasklig, but for some reason I can't stomach the dotted zero, so I was wondering if you'd consider adding a version with it slashed, kind of like what [Meslo LG](https://github.com/andreberg/Meslo-Font) does. 

Thanks.

**Comment by BornForFever** [comment]
If you're using VS code, you can add `"editor.fontLigatures": "'zero'"` to the `settings.json` file.

**Comment by ron-wolf** [comment]
@BornForFever Any idea how this works, or if the same or similar is available in other editors? A Google search term would be plenty 😄

**Comment by BornForFever** [comment]
An OpenType feature.

**Comment by ron-wolf** [comment]
Thanks! In case anyone else ends up on this issue whilst using Sublime Text, check out sublimehq/sublime_text#2302. @tonsky, the custodian of [Fira Code](https://github.com/tonsky/FiraCode), also chimed in.

**Comment by i-tu** [comment]
This issue seems to be resolved by the slashed zero already present in the font, closing this :)
