### ISSUE TITLE
Please, add Fraktur and Georgian glyphs and cursive italic

### ISSUE THREAD

**Issue by gusbemacbe** [i-tu/Hasklig#88]
Hello,

* Georgian alphabet: https://www.wikiwand.com/en/Georgian_scripts
* Similar to Fraktur glyphs:
   * Fraktur from Pragmata Pro: https://www.fsd.it/shop/fonts/pragmatapro/#tab-1449666101445-7-7
   * Franktur Unicode: https://www.wikiwand.com/en/Letterlike_Symbols
* Similar to cursive italic: Operator Mono Italic: https://www.typography.com/fonts/operator/webfonts/operatormono-lightitalic/

**Comment by i-tu** [comment]
Hi @gusbemacbe, thanks for your suggestions.

Hasklig is a fork of Source Code Pro adding ligatures. Unless these glyphs make their way into Source Code Pro, it is very unlikely they will become part of Hasklig. You should ask about their plans at https://github.com/adobe-fonts/source-code-pro

**Comment by gusbemacbe** [comment]
OK, I have just posted a new issue there.
