### ISSUE TITLE
Building TTF files does not seem to work

### ISSUE THREAD

**Issue by Lugribossk** [i-tu/Hasklig#90]
Attempting to build the TTF files with build.cmd fails with the following error:
`
makeotf [Error] Could not find the input font file at 'C:\Code\Hasklig\\Roman\Black\font.ttf'.
The system cannot find the path specified.
`
That file is indeed not there or anywhere else in the repository, but it does exist in the Source Code Pro repository. Does that mean that TTF is not supported for Hasklig?

**Comment by i-tu** [comment]
@Lugribossk , note that you must first build font instances before building the actual ttf files. This is done with `makeInstancesUFO` see https://github.com/i-tu/Hasklig/blob/master/buildInstances.sh

To understand why, please read the documentation carefully: https://github.com/i-tu/Hasklig#building-the-fonts-from-source
