### ISSUE TITLE
Hasklig not working on OSX 10.12.t And Atom 1.18

### ISSUE THREAD

**Issue by leon-yum** [i-tu/Hasklig#91]
![screen shot 2017-07-22 at 2 19 13 pm](https://user-images.githubusercontent.com/30158970/28494058-c2adb95e-6ee8-11e7-8016-c68a25b9e628.png)

<img width="396" alt="screen shot 2017-07-22 at 2 18 43 pm" src="https://user-images.githubusercontent.com/30158970/28494055-bbf05270-6ee8-11e7-85d4-c3c40c79a207.png">

<img width="468" alt="screen shot 2017-07-22 at 2 19 29 pm" src="https://user-images.githubusercontent.com/30158970/28494060-cc6161b2-6ee8-11e7-9925-459036e656dc.png">

**Comment by lrecknagel** [comment]
It should work with only type "Hasklig" as font family. Works perfectly for me.

**Comment by i-tu** [comment]
@leon-yum , the screenshot you have included has expected behaviour. Notice the arrow in `() => {` on line 7. I am closing this for now.
