### ISSUE TITLE
Display corruption in PhpStorm 2017.2.1 on Windows

### ISSUE THREAD

**Issue by Bilge** [i-tu/Hasklig#97]
![absolutely broken](https://user-images.githubusercontent.com/470626/30525681-0bd0b4aa-9c03-11e7-8eb3-ca2b29addaed.png)

**Comment by bushyn** [comment]
https://github.com/tonsky/FiraCode/issues/246#issuecomment-244089963

Deleting duplicate fonts will probably help.

**Comment by i-tu** [comment]
Can't really duplicate this, will close for now.
